"""Build, serialize and read the OKF knowledge bundle (`knowledge/` · §9/§12).

The bundle is TWO deterministic YAML files under a project's `knowledge/` directory:

- `modules.yaml`  — the module map (`generator.build_module_map`).
- `manifest.yaml` — bundle version, generated-at, source commit, and a sha256 per canonical
                    source file. This manifest is the staleness detector (§12).

Determinism is enforced at write time: `yaml.safe_dump(sort_keys=True)` over model dumps,
with every list pre-sorted in the generator — so the same repo state serializes to
byte-identical bytes (Phase 1's non-negotiable property; a test pins it).
"""

from __future__ import annotations

import contextlib
import hashlib
import logging
from pathlib import Path

import yaml

from openfactory.knowledge.contracts import (
    BUNDLE_VERSION,
    BundleManifest,
    KnowledgeBundle,
    ModuleMap,
    SourceChecksum,
    UnreadExtension,
)
from openfactory.knowledge.generator import (
    BUNDLE_MANIFEST_FILE,
    BUNDLE_MODULES_FILE,
    build_module_map,
    canonical_source_files,
    survey_extensions,
)

_log = logging.getLogger("openfactory.knowledge.bundle")

BUNDLE_DIRNAME = "knowledge"
# Aliased from the generator, which needs the same two names to keep its own output out of
# the "files I did not read" survey. One definition, so they cannot drift apart.
MODULES_FILE = BUNDLE_MODULES_FILE
MANIFEST_FILE = BUNDLE_MANIFEST_FILE

_GENERATED_BANNER = (
    "# GENERATED by `openfactory knowledge build` — do NOT edit by hand.\n"
    "# The code is the ground truth (docs/knowledge-layer.md §7); this map only accelerates\n"
    "# navigation to it. Regenerate after a merge that changes the sources.\n"
)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def compute_checksums(repo_path: Path) -> list[SourceChecksum]:
    """A sha256 per canonical source file, sorted by path — the §12 staleness fingerprint.
    Best-effort: an unreadable file is skipped (it simply won't be tracked for drift)."""
    repo = Path(repo_path).expanduser().resolve()
    out: list[SourceChecksum] = []
    for rel in canonical_source_files(repo):
        try:
            digest = _sha256((repo / rel).read_bytes())
        except OSError as exc:
            _log.warning("knowledge: could not checksum %s (%s)", rel, exc)
            continue
        out.append(SourceChecksum(file=rel.as_posix(), sha256=digest))
    out.sort(key=lambda c: c.file)
    return out


def build_bundle(repo_path: Path, *, commit: str = "", generated_at: str = "") -> KnowledgeBundle:
    """Assemble the whole bundle: the module map + the staleness manifest. `commit` and
    `generated_at` are passed in (never read from git/clock here) so the build is a pure
    function of its inputs — identical inputs, identical bundle."""
    module_map = build_module_map(repo_path, commit=commit)
    survey = survey_extensions(repo_path)
    manifest = BundleManifest(
        bundle_version=BUNDLE_VERSION,
        generated_at=generated_at,
        source_commit=commit,
        checksums=compute_checksums(repo_path),
        files_read=survey.files_read,
        files_unread=survey.files_unread,
        unread_extensions=[
            UnreadExtension(suffix=suffix, files=count) for suffix, count in survey.unread
        ],
        unreadable_paths=survey.unreadable,
    )
    return KnowledgeBundle(manifest=manifest, module_map=module_map)


def _dump(data: object) -> str:
    """Deterministic YAML: keys sorted, block style, no aliases, unicode preserved."""
    return yaml.safe_dump(data, sort_keys=True, default_flow_style=False, allow_unicode=True)


def derived_key(bundle: KnowledgeBundle) -> str:
    """A fingerprint of everything the bundle DERIVES FROM THE SOURCES, with the provenance
    stamps (`generated_at`, `source_commit`, per-module `source.commit`) blanked out.

    This is what makes the persist-per-commit model (§22 D-1/D-2) terminate. The bundle is
    generated from commit X and then COMMITTED, which necessarily creates a later commit Y — so
    the stamps are different by construction on every single regeneration. Regenerating on "the
    sources changed" is right; regenerating on "the stamp moved" is a self-feeding loop:
    build@X → commit Y → post-merge trigger → build@Y → commit Z → … forever, each one a real
    commit on the client's `main`. Comparing THIS key instead makes a stamp-only rebuild a
    no-op, so the pipeline converges after exactly one commit per real source change."""
    payload = bundle.module_map.model_dump(mode="json")
    payload["source_commit"] = ""
    for m in payload.get("modules") or []:
        if isinstance(m.get("source"), dict):
            m["source"]["commit"] = ""
    payload["checksums"] = [c.model_dump(mode="json") for c in bundle.manifest.checksums]
    payload["bundle_version"] = bundle.manifest.bundle_version
    # Coverage belongs in the key, not outside it. A merge that adds three `.java` files
    # changes NO checksum (they are not canonical sources) — so without this the declaration
    # on disk would keep saying "no .java here" forever, and the bundle would understate its
    # blindness exactly where the declaration exists to prevent that. `None` (not declared)
    # is kept distinct from `[]` (declared, nothing unread), or an old bundle would compare
    # equal to a freshly surveyed one and never gain the declaration.
    payload["files_read"] = bundle.manifest.files_read
    payload["files_unread"] = bundle.manifest.files_unread
    payload["unread_extensions"] = (
        None if bundle.manifest.unread_extensions is None
        else [e.model_dump(mode="json") for e in bundle.manifest.unread_extensions]
    )
    # And for the same reason: a directory that BECOMES unreadable changes no checksum (its
    # files were never canonical sources) and no extension count (it contributes to neither
    # side of the split), so leaving it out of the key would let the manifest keep claiming a
    # clean walk long after the walk stopped being clean. `None` (never walked) stays distinct
    # from `[]` (walked, every directory opened) here too.
    payload["unreadable_paths"] = (
        None if bundle.manifest.unreadable_paths is None
        else list(bundle.manifest.unreadable_paths)
    )
    return _dump(payload)


def write_bundle(bundle: KnowledgeBundle, repo_path: Path, *, force: bool = False) -> Path | None:
    """Write `knowledge/modules.yaml` + `knowledge/manifest.yaml` into the repo. Returns the
    bundle directory, or **None when nothing was written** because the bundle derives from
    exactly the same sources as the one already on disk (see `derived_key`) — the caller then
    knows there is nothing to commit. `force=True` writes unconditionally (stamp refresh).

    Idempotent — rewriting an unchanged repo yields identical bytes."""
    repo = Path(repo_path).expanduser().resolve()
    dest = repo / BUNDLE_DIRNAME
    if not force:
        existing = read_bundle_dir(dest)
        if existing is not None and derived_key(existing) == derived_key(bundle):
            _log.info("knowledge: sources unchanged — bundle left as-is (nothing to commit)")
            return None
    dest.mkdir(parents=True, exist_ok=True)
    # REPLACED, NEVER TRUNCATED. A RepoCache snapshot is built with `copy_function=os.link`, so
    # every file shares its inode with the hidden master (and with any snapshot a concurrent
    # reader holds): an in-place `write_text` there rewrites ALL of them through the link.
    # `os.replace` of a fresh temp file swaps in a NEW inode instead — atomic, and the master
    # keeps the bytes it had (adversarial review, 2026-08-13).
    _write_atomic(dest / MODULES_FILE,
                  _GENERATED_BANNER + _dump(bundle.module_map.model_dump(mode="json")))
    _write_atomic(dest / MANIFEST_FILE,
                  _GENERATED_BANNER + _dump(bundle.manifest.model_dump(mode="json")))
    return dest


def _write_atomic(path: Path, text: str) -> None:
    import os
    import tempfile

    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise


def read_bundle(repo_path: Path) -> KnowledgeBundle | None:
    """Load a previously written bundle from a repo's `knowledge/` dir. Returns None if it
    is absent or unreadable/corrupt — the consumer then degrades to searching the code
    directly (§12 fail-safe), never crashing on a bad bundle."""
    repo = Path(repo_path).expanduser().resolve()
    return read_bundle_dir(repo / BUNDLE_DIRNAME)


def read_bundle_dir(bundle_dir: Path) -> KnowledgeBundle | None:
    """Load a bundle from an explicit directory. Best-effort (see `read_bundle`)."""
    mod_file = bundle_dir / MODULES_FILE
    man_file = bundle_dir / MANIFEST_FILE
    if not (mod_file.is_file() and man_file.is_file()):
        return None
    try:
        module_map = ModuleMap(**(yaml.safe_load(mod_file.read_text(encoding="utf-8")) or {}))
        manifest = BundleManifest(**(yaml.safe_load(man_file.read_text(encoding="utf-8")) or {}))
    except (yaml.YAMLError, ValueError, TypeError) as exc:
        _log.warning("knowledge: bundle at %s is unreadable (%s) — ignoring", bundle_dir, exc)
        return None
    return KnowledgeBundle(manifest=manifest, module_map=module_map)
