"""The inventory: every file, its kind, and why — and the remainder COUNTED (OKF §6.1).

A bundle's coverage table divided by the module map: "5 of 412 modules described" — and a module
row cannot say which FILES were never asked about. The reference format's pilot found what that
hides: a convention glob returned fifteen files that were 100 % commented out and missed the
sixty-four live entry points beside them, and a bundle with four concepts over eighty-two files
exited clean because every kind had a reason. So the inventory is exhaustive by construction — a
file no rule places is `unclassified` and a row, a directory the walk could not open is named, a
walk that hit its ceiling says so — and the coverage table gains one row per kind, with the
exemption stated and the rows nothing excuses marked `excused: False`.

Measured on the core's own tree before any of this: 866 files, and the first cut of the rules
placed `.git` (a worktree's pointer FILE), `registry.yaml.example` and three `*.Dockerfile`s in
`unclassified`, called thirty-six `__init__.py` entry points, and reported a hundred credential
risks — `token_env: "SLACK_BOT_TOKEN"` and `token_pool.ssm` among them. The rules below are the
ones that survived that measurement; the guards pin each of those cuts.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from openfactory.knowledge import bundle as _bundle
from openfactory.knowledge import inventory as inv
from openfactory.knowledge.contracts import Concept, ConceptSource, Inventory
from openfactory.knowledge.inventory import (
    BUDGET_DID_NOT_REACH,
    INVENTORY_FILE,
    INVENTORY_SUMMARY_FILE,
    NO_EXEMPTION,
    WHY_NOT,
    classify,
    coverage_by_kind,
    inventory_gaps,
    read_inventory,
    render_inventory_md,
    take_inventory,
    write_inventory,
)

ROOT = Path(__file__).resolve().parent.parent


def _repo(tmp_path: Path, files: dict[str, str | bytes]) -> Path:
    for rel, body in files.items():
        path = tmp_path / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(body, bytes):
            path.write_bytes(body)
        else:
            path.write_text(body, encoding="utf-8")
    return tmp_path


DEAD = "// a\n// b\n// c\n// d\n// e\n// f\n"
BARREL = "from .a import A\nfrom .b import B\n\n__all__ = [\n    A,\n    B,\n]\n"


# --- the rules ------------------------------------------------------------------------------

@pytest.mark.parametrize("rel,body,kind,why", [
    ("node_modules/left-pad/index.js", "module.exports = 1", "vendored", "node_modules"),
    ("package-lock.json", "{}", "generated", "lockfile"),
    ("web/app.min.js", "x", "generated", ".min.js"),
    ("gen/model.py", "# Code generated by protoc. DO NOT EDIT.\nx = 1\n", "generated", "first"),
    (".github/workflows/ci.yml", "on: push", "pipeline-definition", ".github/workflows"),
    ("azure-pipelines.yml", "trigger: main", "pipeline-definition", "pipeline file"),
    (".gitignore", "*.pyc", "repo-metadata", "repository metadata"),
    (".git", "gitdir: /elsewhere", "repo-metadata", "repository metadata"),
    (".vscode/settings.json", "{}", "repo-metadata", ".vscode"),
    ("Dockerfile", "FROM x", "build-definition", "build file"),
    ("docker/worker.Dockerfile", "FROM x", "build-definition", "build file"),
    ("api/Api.csproj", "<Project/>", "build-definition", "build file"),
    ("pyproject.toml", "[tool]", "build-definition", "build file"),
    ("tests/test_x.py", "def test(): pass", "test", "test by path"),
    ("src/foo_test.go", "package x", "test", "test by path"),
    ("db/migrations/001_init.sql", "create table t(i int)", "data-definition", "migrations"),
    ("api/schema.graphql", "type Q { a: Int }", "data-definition", ".graphql"),
    ("migrations/0001_initial.py", "operations = []", "data-definition", "migrations"),
    ("docs/adr/0001.md", "# one", "documentation", "documentation"),
    ("README", "hello", "documentation", "documentation"),
    ("web/App.tsx", "export default 1", "ui-component", ".tsx"),
    ("web/index.html", "<html></html>", "markup", ".html"),
    ("web/app.scss", "a {}", "style", ".scss"),
    ("bin/run.sh", "#!/bin/sh\necho hi", "script", ".sh"),
    ("config/app.yaml", "a: 1", "configuration", ".yaml"),
    ("deploy/registry.yaml.example", "a: 1", "configuration", "example of `.yaml`"),
    (".env.local", "A=1", "configuration", "configuration"),
    ("assets/logo.png", b"\x89PNG\r\n\x1a\n\x00\x00", "asset", ".png"),
    ("src/main.py", "print(1)", "entry-point", "entry-point name"),
    ("src/billing/rules.py", "def charge():\n    return 1\n", "code", ".py"),
    ("src/pkg/__init__.py", BARREL, "re-export", "barrel"),
    ("src/pkg/empty/__init__.py", "", "code", ".py"),
    ("src/old/Legacy.cs", DEAD, "dead-code", "6 of 6"),
    ("weird.xyz", "?", "unclassified", ".xyz"),
])
def test_the_rule_and_its_reason(rel, body, kind, why):
    """First match wins, and `kind_reason` names the rule — the inventory's one failure mode
    (a wrong kind) is visible where it was decided. Through `classify` directly: the walk prunes
    `node_modules/` and `.vscode/` before a rule ever sees them, and the rule must still be right
    for the checkout that does not prune (a bundle read back, a path cited by a concept)."""
    got_kind, reason = classify(rel, text=body if isinstance(body, str) else None)
    assert got_kind == kind, (got_kind, reason)
    assert why in reason, reason


def test_every_file_is_a_row_and_the_kinds_sum_to_the_total(tmp_path):
    files = {"a.py": "x = 1", "b/c.md": "# c", "d.xyz": "?", "e/f.yaml": "k: v",
             "tests/test_a.py": "def test(): pass"}
    taken = take_inventory(_repo(tmp_path, files))
    assert sorted(r.path for r in taken.files) == sorted(files)
    assert sum(taken.by_kind.values()) == len(files)
    assert all(r.kind_reason for r in taken.files), "a row with no reason is a guess"


def test_a_file_no_rule_places_is_counted_not_dropped(tmp_path):
    taken = take_inventory(_repo(tmp_path, {"a.py": "x = 1", "thing.xyz": "?", "other.qqq": "!"}))
    assert taken.unclassified == ["other.qqq", "thing.xyz"]
    assert taken.by_kind["unclassified"] == 2
    kinds = [g.kind for g in inventory_gaps(taken)]
    assert kinds.count("unclassified") == 2, "each unclassified file is its own gap"


def test_dead_code_needs_a_floor(tmp_path):
    """Three comment lines are a header, not a dead file."""
    taken = take_inventory(_repo(tmp_path, {"a.cs": "// a\n// b\n// c\n"}))
    assert taken.files[0].kind == "code"


def test_the_pilots_finding_a_fully_commented_file_is_dead_code_and_a_gap(tmp_path):
    """Fifteen `Functions/**/*.cs` that were 100 % commented out — a convention glob counted
    them as functions. Content shape says otherwise, whatever the folder is called."""
    taken = take_inventory(_repo(tmp_path, {"Functions/Handler.cs": DEAD}))
    assert taken.files[0].kind == "dead-code"
    gap = next(g for g in inventory_gaps(taken) if g.kind == "dead-code")
    assert gap.path == "Functions/Handler.cs" and "6 of 6" in gap.detail


def test_the_fingerprint_is_the_checkers_own(tmp_path):
    body = "def charge():\n    return 1\n"
    taken = take_inventory(_repo(tmp_path, {"rules.py": body}))
    assert taken.files[0].fingerprint == _bundle._sha256(body.encode("utf-8"))


def test_lines_are_counted_with_or_without_a_final_newline(tmp_path):
    taken = take_inventory(_repo(tmp_path, {"a.py": "1\n2\n3\n", "b.py": "1\n2\n3"}))
    assert {r.path: r.lines for r in taken.files} == {"a.py": 3, "b.py": 3}


def test_an_unreadable_directory_is_declared_not_skipped(tmp_path, monkeypatch):
    """`os.walk` swallows a directory it cannot open — the survey's C-49 collapse. The inventory
    carries the survey's own declaration, and it becomes a gap."""
    from openfactory.onboarding import context

    real = context._collect_files

    def blind(repo, max_files):
        files = real(repo, max_files)
        return files.model_copy(update={"unreadable": ["vendor/blob"], "truncated": True})

    monkeypatch.setattr(context, "_collect_files", blind)
    taken = take_inventory(_repo(tmp_path, {"a.py": "x = 1"}))
    assert taken.unreadable == ["vendor/blob"] and taken.truncated
    kinds = {g.kind: g for g in inventory_gaps(taken)}
    assert kinds["unreadable"].path == "vendor/blob" and "not as empty" in kinds["unreadable"].detail
    assert "truncated" in kinds and "not inventoried" in kinds["truncated"].detail


def test_a_file_that_cannot_be_read_is_an_error_row(tmp_path, monkeypatch):
    real = inv._read

    def half_blind(path):
        return (None, None) if path.name == "b.py" else real(path)

    monkeypatch.setattr(inv, "_read", half_blind)
    taken = take_inventory(_repo(tmp_path, {"a.py": "x = 1", "b.py": "y = 2"}))
    assert taken.errors == ["b.py"]
    row = next(r for r in taken.files if r.path == "b.py")
    assert row.kind == "code" and row.kind_reason.endswith("(could not be read)")
    assert any(g.kind == "unreadable" and g.path == "b.py" for g in inventory_gaps(taken))


# --- the credential scan ----------------------------------------------------------------------

def test_a_literal_password_is_a_high_risk_and_the_value_is_never_recorded(tmp_path):
    taken = take_inventory(_repo(tmp_path, {"settings.py": 'PASSWORD = "hunter2hunter2"\n'}))
    (risk,) = taken.secret_risks
    assert (risk.path, risk.key, risk.line, risk.severity, risk.kind) == (
        "settings.py", "PASSWORD", 1, "high", "code")
    assert "hunter2hunter2" not in taken.model_dump_json()
    assert "hunter2hunter2" not in render_inventory_md(taken)
    gap = next(g for g in inventory_gaps(taken) if g.kind == "credential-risk")
    assert "`PASSWORD` at line 1" in gap.detail and "hunter2hunter2" not in gap.detail


def test_a_placeholder_is_low_and_a_lookup_is_no_literal_at_all(tmp_path):
    taken = take_inventory(_repo(tmp_path, {
        "a.yaml": 'password: "${DB_PASSWORD}"\n',
        "b.json": '{"token": "<your-token-here>"}\n',
        "c.py": 'api_key = "changeme-please"\n',
        "d.py": 'token = os.getenv("TOKEN")\n',
    }))
    assert {r.path: r.severity for r in taken.secret_risks} == {
        "a.yaml": "low", "b.json": "low", "c.py": "low"}, "d.py assigns no literal"


def test_a_key_that_names_a_variable_is_not_a_secret(tmp_path):
    """`slack_bot_token_env: "SLACK_BOT_TOKEN"` names where the token LIVES; `token_pool.ssm`
    is a registry key that happens to contain the word. Measured: a hundred of these on the
    core's own tree before the secret word had to END the key."""
    taken = take_inventory(_repo(tmp_path, {
        "registry.yaml": 'slack_bot_token_env: "SLACK_BOT_TOKEN"\n',
        "plugins.py": '"token_pool.ssm": "openfactory.adapters.agent.ssm_pool"\n',
        "names.py": 'PANEL_TOKENS = "OPENFACTORY_PANEL_TOKENS"\n',
    }))
    assert [(r.path, r.severity) for r in taken.secret_risks] == [("names.py", "low")]


def test_a_literal_in_a_test_or_a_document_is_listed_but_low(tmp_path):
    """Seventy-four highs on the core's own tree, and every one a fixture or a docs example."""
    taken = take_inventory(_repo(tmp_path, {
        "tests/test_x.py": 'PASSWORD = "hunter2hunter2"\n',
        "docs/setup.md": 'token: "abcdefghijklmnop"\n',
    }))
    assert {r.path: (r.severity, r.kind) for r in taken.secret_risks} == {
        "tests/test_x.py": ("low", "test"), "docs/setup.md": ("low", "documentation")}


def test_a_private_key_block_and_an_aws_key_are_high(tmp_path):
    taken = take_inventory(_repo(tmp_path, {
        "id_rsa.pem": "-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n",
        "conf.py": 'x = "AKIAIOSFODNN7EXAMPLE"\n',
    }))
    assert {r.key: r.severity for r in taken.secret_risks} == {
        "PRIVATE KEY": "high", "AWS access key": "high"}


def test_binary_files_are_not_scanned(tmp_path):
    taken = take_inventory(_repo(tmp_path, {"blob.bin": b"password=\"abcdefghij\"\x00\x01"}))
    assert taken.files[0].kind == "asset" and taken.secret_risks == []


# --- coverage --------------------------------------------------------------------------------

def _concept(*paths: str) -> Concept:
    return Concept(type="policy", title="t", description="d", what_it_does="w",
                   sources=[ConceptSource(repo="r", path=p, commit="c", fingerprint="f",
                                          lines="1-2") for p in paths])


def _taken(tmp_path: Path) -> Inventory:
    return take_inventory(_repo(tmp_path, {
        "src/a.py": "x = 1", "src/b.py": "y = 2", "tests/test_a.py": "def test(): pass",
        "app.yaml": "k: v", "odd.xyz": "?"}))


def test_one_row_per_kind_with_the_exemption_or_the_debt(tmp_path):
    rows = {r.kind: r for r in coverage_by_kind(_taken(tmp_path), [_concept("src/a.py")])}
    assert set(rows) == {"code", "test", "configuration", "unclassified"}
    assert (rows["code"].inventoried, rows["code"].concepts, rows["code"].reason) == (2, 1, "")
    assert rows["test"].concepts == 0 and rows["test"].excused is True
    assert rows["test"].reason == WHY_NOT["test"][0]
    assert rows["unclassified"].reason == NO_EXEMPTION and rows["unclassified"].excused is False


def test_code_the_budget_did_not_reach_is_explained_but_not_excused(tmp_path):
    rows = {r.kind: r for r in coverage_by_kind(_taken(tmp_path), [])}
    assert rows["code"].reason == BUDGET_DID_NOT_REACH and rows["code"].excused is False


def test_concepts_are_counted_per_concept_not_per_file(tmp_path):
    rows = {r.kind: r for r in coverage_by_kind(_taken(tmp_path), [_concept("src/a.py",
                                                                             "src/b.py")])}
    assert rows["code"].concepts == 1


def test_the_backfills_coverage_gains_the_kind_rows(tmp_path):
    from openfactory.onboarding.onboard import _coverage
    from tests.test_a_concept_is_earned_not_declared import _survey

    survey = _survey(tmp_path)
    without = _coverage(survey, [], budget=1)
    assert [r.kind for r in without] == ["module"]
    with_rows = _coverage(survey, [], budget=1, inventory=_taken(tmp_path))
    assert [r.kind for r in with_rows] == ["module", "code", "configuration", "test",
                                           "unclassified"]


# --- the files -----------------------------------------------------------------------------

def test_write_and_read_round_trip(tmp_path):
    taken = _taken(tmp_path / "src")
    written = write_inventory(tmp_path / "bundle", taken)
    assert [p.name for p in written] == [INVENTORY_FILE, INVENTORY_SUMMARY_FILE]
    assert read_inventory(tmp_path / "bundle") == taken
    assert read_inventory(tmp_path / "nowhere") is None


def test_an_unknown_schema_is_none_not_a_guess(tmp_path):
    (tmp_path / INVENTORY_FILE).write_text(json.dumps({"schema_version": "9", "files": []}))
    assert read_inventory(tmp_path) is None


def test_the_summary_names_every_remainder(tmp_path, monkeypatch):
    from openfactory.onboarding import context

    real = context._collect_files
    monkeypatch.setattr(context, "_collect_files", lambda r, m: real(r, m).model_copy(
        update={"unreadable": ["locked"]}))
    taken = take_inventory(_repo(tmp_path, {"odd.xyz": "?", "s.py": 'SECRET = "abcdefghijk"\n'}))
    text = render_inventory_md(taken)
    assert "## Unclassified" in text and "`odd.xyz`" in text
    assert "`s.py:1` — `SECRET` (high" in text and "abcdefghijk" not in text
    assert "## Could not read" in text and "`locked/`" in text


# --- the backfill and the CLI ---------------------------------------------------------------

def test_the_backfill_writes_the_inventory_beside_the_concepts(tmp_path):
    """End to end through `_write_concepts`: the inventory is taken before the agent pass, its
    gaps join the manifest's, its rows join the coverage table, and both files land in the
    bundle beside `index.md`."""
    from types import SimpleNamespace

    import yaml

    from openfactory.knowledge.okf import OKF_MANIFEST_FILE
    from openfactory.knowledge.pipeline import okf_subpath
    from openfactory.onboarding.onboard import _write_concepts
    from tests.test_a_concept_is_earned_not_declared import _answer, _survey
    from tests.test_a_concept_is_earned_not_declared import _repo as _git_repo

    (tmp_path / "src").mkdir()
    repo = _git_repo(tmp_path / "src")
    (repo / "odd.xyz").write_text("?", encoding="utf-8")
    docs = tmp_path / "docs"
    docs.mkdir()
    project = SimpleNamespace(name="demo", forge=SimpleNamespace(repo="acme/api", kind="github"),
                              tracker=None)
    written = _write_concepts(project, _survey(repo), repo, docs,
                              ask_fn=lambda _p: _answer(), commit="deadbee")
    bundle = docs / okf_subpath("acme/api")
    assert (bundle / INVENTORY_FILE).is_file() and (bundle / INVENTORY_SUMMARY_FILE).is_file()
    assert any(w.endswith(INVENTORY_FILE) for w in written)
    manifest = yaml.safe_load((bundle / OKF_MANIFEST_FILE).read_text(encoding="utf-8"))
    kinds = {row["kind"]: row for row in manifest["coverage"]}
    assert kinds["code"]["inventoried"] == 1 and kinds["code"]["concepts"] == 1, kinds
    assert kinds["unclassified"]["excused"] is False
    assert any(g["kind"] == "unclassified" and g["path"] == "odd.xyz" for g in manifest["gaps"])
    assert "| unclassified | 1 | 0 |" in (bundle / "index.md").read_text(encoding="utf-8")


def test_the_cli_takes_an_inventory_without_a_project(tmp_path):
    from typer.testing import CliRunner

    from openfactory.cli import app

    repo = _repo(tmp_path / "r", {"a.py": "x = 1", "odd.xyz": "?"})
    out = CliRunner().invoke(app, ["knowledge", "inventory", str(repo), "--out",
                                  str(tmp_path / "b")])
    assert out.exit_code == 0, out.output
    assert "files: 2" in out.output and "unclassified: odd.xyz" in out.output
    assert (tmp_path / "b" / INVENTORY_FILE).is_file()
    missing = CliRunner().invoke(app, ["knowledge", "inventory", str(tmp_path / "nope")])
    assert missing.exit_code == 2, missing.output


def test_the_walk_is_the_surveys_own():
    """One walk, not two: the inventory reuses `_collect_files` rather than owning a second
    pruning rule set the module map would drift away from."""
    src = (ROOT / "openfactory/knowledge/inventory.py").read_text(encoding="utf-8")
    assert "from openfactory.onboarding.context import _collect_files" in src
    assert "os.walk" not in src
